"""Generate charset.mbt from CPython's encodings.aliases table.

Usage: python3 tools/gen_charset.py > charset.mbt && moon fmt
"""
import encodings.aliases as a

LIMITS = {'ascii': '0x7f', 'latin_1': '0xff'}
UNICODE = ['utf_8', 'utf_8_sig', 'utf_16', 'utf_16_le', 'utf_16_be',
           'utf_32', 'utf_32_le', 'utf_32_be']
CODECS = list(LIMITS) + UNICODE


def arms(names_for, indent='    '):
    out = []
    for codec in CODECS:
        names = names_for(codec)
        if names:
            out.append(indent + ' | '.join('"%s"' % n for n in sorted(names))
                       + ' => Some("%s")' % codec)
    out.append(indent + '_ => None')
    return '\n'.join(out)


print('''// Generated by tools/gen_charset.py from CPython's `encodings.aliases`.
// Charset handling for `HtmlDiff::make_file`, emulating Python's
// `str.encode(charset, "xmlcharrefreplace")` for the codecs listed below.

///|
/// Python's `encodings.normalize_encoding` followed by lowercasing: runs of
/// characters other than ASCII letters, digits and `.` become a single `_`,
/// and leading/trailing ones are dropped.
fn normalize_encoding(name : String) -> String {
  let buf = StringBuilder()
  let mut punct = false
  for c in name.to_lower() {
    if c is ('a'..='z' | '0'..='9' | '.') {
      if punct && buf.to_string() != "" {
        buf.write_char('_')
      }
      buf.write_char(c)
      punct = false
    } else {
      punct = true
    }
  }
  buf.to_string()
}

///|
/// Python's `encodings.aliases.aliases` restricted to the supported codecs.
fn codec_alias(name : String) -> String? {
  match name {
%s
  }
}

///|
/// Resolves a charset name to a Python codec name like `encodings.search_function`:
/// the alias table is consulted for the normalized name and for the name
/// with `.` replaced by `_`, while a canonical codec module name must match
/// the normalized name exactly. Returns `None` for codecs this package does
/// not know about.
fn resolve_codec(charset : String) -> String? {
  let norm = normalize_encoding(charset)
  match codec_alias(norm) {
    Some(codec) => return Some(codec)
    None => ()
  }
  match codec_alias(norm.replace_all(old=".", new="_")) {
    Some(codec) => return Some(codec)
    None => ()
  }
  match norm {
%s
  }
}

///|
/// Replaces characters that `charset` cannot encode by `&#NNN;` references,
/// emulating Python's `encode(charset, 'xmlcharrefreplace')` for ASCII,
/// Latin-1 and the UTF-8/16/32 codecs. Unknown charsets are assumed to encode
/// all of Unicode.
fn xml_charref_replace(s : String, charset : String) -> String {
  let max_code = match resolve_codec(charset) {
    Some("ascii") => 0x7f
    Some("latin_1") => 0xff
    Some(_) => 0x10ffff
    None => return s
  }
  let buf = StringBuilder()
  for c in s {
    let code = c.to_int()
    // lone surrogates cannot be encoded by any of these codecs
    if code > max_code || (code >= 0xd800 && code <= 0xdfff) {
      buf.write_string("&#\\{code};")
    } else {
      buf.write_char(c)
    }
  }
  buf.to_string()
}''' % (arms(lambda c: [k for k, v in a.aliases.items() if v == c]),
        arms(lambda c: [c])))
